name: CI Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  ci_test:
    name: CI Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4

      - name: Test
        run: make test
